LineLength:
  Enabled: true
  Max: 129
SpaceAroundBraces:
  Enabled: false
StringLiterals:
  Enabled: false
NestedTernaryOperator:
  Enabled: false
HashSyntax:
  Enabled: false
AlignParameters:
  Enabled: false
Lambda:
  Enabled: false
EndAlignment:
  Enabled: false
MethodLength:
  Max: 50
  CountComments: false




